CREATE TABLE IF NOT EXISTS public.university_campus (
  campus_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES public.university(university_id) ON DELETE CASCADE,
  name VARCHAR(160) NOT NULL,
  address TEXT NOT NULL DEFAULT '',
  contact_info VARCHAR(160) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT university_campus_university_name_key UNIQUE (university_id, name)
);

ALTER TABLE public.student
  ADD COLUMN IF NOT EXISTS campus_id BIGINT
  REFERENCES public.university_campus(campus_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS student_campus_id_idx ON public.student(campus_id);

INSERT INTO public.university (name, address, contact_info)
VALUES (
  'FPT University',
  'FPT University Vietnam',
  'contact@fpt.edu.vn'
)
ON CONFLICT (name) DO UPDATE
SET contact_info = EXCLUDED.contact_info;

INSERT INTO public.university_campus (university_id, name, address, contact_info)
SELECT university.university_id, source.name, source.address, source.contact_info
FROM (
  VALUES
    ('Ha Noi', 'Khu Giao duc va Dao tao, Khu Cong nghe cao Hoa Lac, Km29 Dai lo Thang Long, Xa Hoa Lac, TP. Ha Noi', '(024) 7300 5588'),
    ('TP. Ho Chi Minh', 'Lo E2a-7, Duong D1, Khu Cong nghe cao, Phuong Tang Nhon Phu, TP. Ho Chi Minh', '(028) 7300 5588'),
    ('Da Nang', 'Khu do thi cong nghe FPT Da Nang, Phuong Ngu Hanh Son, TP. Da Nang', '(0236) 730 0999'),
    ('Can Tho', 'So 600, duong Nguyen Van Cu (noi dai), Phuong An Binh, TP. Can Tho', '(0292) 730 3636'),
    ('Quy Nhon', 'Khu do thi moi An Phu Thinh, Phuong Quy Nhon Dong, Tinh Gia Lai', '(0256) 7300 999')
) AS source(name, address, contact_info)
JOIN public.university ON university.name = 'FPT University'
ON CONFLICT (university_id, name) DO UPDATE
SET
  address = EXCLUDED.address,
  contact_info = EXCLUDED.contact_info;

CREATE OR REPLACE FUNCTION public.create_student_profile_for_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id BIGINT;
  v_role VARCHAR;
  v_full_name TEXT;
  v_student_code TEXT;
  v_university_id BIGINT;
  v_campus_id BIGINT;
BEGIN
  UPDATE public.app_user
  SET auth_id = NEW.id
  WHERE email = NEW.email AND auth_id IS NULL
  RETURNING user_id, role INTO v_user_id, v_role;

  IF v_user_id IS NULL THEN
    INSERT INTO public.app_user (auth_id, email, role)
    VALUES (NEW.id, NEW.email, 'student')
    RETURNING user_id, role INTO v_user_id, v_role;
  END IF;

  IF v_role <> 'student' THEN
    RETURN NEW;
  END IF;

  v_full_name := NULLIF(TRIM(NEW.raw_user_meta_data ->> 'full_name'), '');
  v_student_code := UPPER(NULLIF(TRIM(NEW.raw_user_meta_data ->> 'student_code'), ''));
  IF COALESCE(NEW.raw_user_meta_data ->> 'university_id', '') ~ '^\d+$' THEN
    v_university_id := (NEW.raw_user_meta_data ->> 'university_id')::BIGINT;
  END IF;
  IF COALESCE(NEW.raw_user_meta_data ->> 'campus_id', '') ~ '^\d+$' THEN
    SELECT campus_id INTO v_campus_id
    FROM public.university_campus
    WHERE campus_id = (NEW.raw_user_meta_data ->> 'campus_id')::BIGINT
      AND university_id = v_university_id;
  END IF;

  IF EXISTS (SELECT 1 FROM public.student WHERE user_id = v_user_id) THEN
    RETURN NEW;
  END IF;

  IF v_full_name IS NOT NULL
    AND v_student_code IS NOT NULL
    AND EXISTS (SELECT 1 FROM public.university WHERE university_id = v_university_id) THEN
    INSERT INTO public.student (
      user_id, university_id, campus_id, name, email, student_code, phone
    ) VALUES (
      v_user_id, v_university_id, v_campus_id, v_full_name, NEW.email, v_student_code, ''
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_student_profile ON auth.users;

CREATE TRIGGER on_auth_user_created_student_profile
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.create_student_profile_for_auth_user();
